travis:
  secure:
    BINSTAR_TOKEN: DQ036KVU8rgz1a+Dv3PqF+bTqtMkqrxB1OGEJI8xqI6agBW22IvC5mJ2mRHIVKmAG+7PGvdsxXVfwDb2hgSRdlI9ti5HVtG+QyXw392+D+1ixsgXbHZxiZlTjFWxpYQZR/03+gaUHCoZG6+QkNo+KM/2bR20dwMOMa373907Z6Z40H4cotWKPRovoWi+kbplFv0uS46eNOt+tWZdeVJ87JZzEIkiI3qxWpJTtDFsM7mD6nh7gnwlXx3SF+ulC0rXzSL9DqQLcp94p7VxxiuBGfch5U1n6bf0HDF5+iVmtpaLR18Y4v1dBICpfBJwpHsSWkVqyglgSWEO5/bB/revL80HPjDs05S3VsHkkBL3/3Efowuwj+vYWJlyz4TxZR5qz1eokflhe798pFp7Q5XgcRbl48bnMW4FqFPQzNZQNlLDccMu/bEfsJoExFCXiX2gmSKn+GnOFe+ppV/yR1rlXJh7H8BPrUqzf29vAMykW4yxGIQfv42JkZXyygLaL5C+uScztjYWbnpSOWmy4yppmwFOijM13+yBYCaBb0h+fislKHzQ9zWfanuPkISE3ziHbl6ibziJ9ecZv5MWtpaD8ess/XZ1776mMeLOAI5VusQQNiG768dp/MhTc4dm4YKuAdQ844+bS2JxtUZl4Ekuo3jTwiuAriE2UGdwyHL+Ryo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
