travis:
  secure:
    BINSTAR_TOKEN: eLpxenEcauGRIRvSI4F+TVK9KM7lv71/mCn2MFaT7IrM4m0Ooja7DTrf3iFjZSDalH/1pJOasjY3eHWBg/c4QRyb4LtnOYfZDyaRiRsGbj/Xl7mljV6Ov0rFLhntPWEvZpfl0fl4h4CLL4rJ2c3t2aP9jmtRnPsnK8likkT/LQFpp/l9Wy92+o5b2kPWOQofZzcl/MLKt7bA95dY4YtwNL4rP0yHmIiWd5VuZbXwK12pMEdMpElQwg9vfrv+MSwQRwOvBgTF/xQ4qiJYge+LC0jXrMLZYbNj2oIsVF4HsYHZl3W4gZOPSJJAu8vBi0MaH2Gj+85V88Tutedu1MsaP6RGDuTBGy7GA0sMXAK1hzi0XlZ1lQm0XGtuRlVot7oulM4/oFXVGe2YaqhUYQCrIEO6k6wTz++8ac5KseG5sdZebQo9bGi/rcWvWBfK43ylNtPfqQilmq6k6zNbmReDcIL74lkb3a8VEkkd8NcaJ9wRiwreMuWSFgygzGpmlMmzLk+FKsj7IXZOOkcBb8Tbhzh1uYAPD3ZWYPCUON3b6XAshpv4jbCuBOOK6XPVinDbiF5y3vCULcSbLbEkUzJ2VOBBzB+Q1L5/GAjXhElCSGfNKaTZSE9LhXm7BMDNeFlbXVKRa/Sb9SYa3fav8lmnIFj/lgoVzulnBZBPHpbUK9U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
