travis:
  secure:
    BINSTAR_TOKEN: FIeYvCuvbECeKUd2enpf6dOQiz11XM+EmQgsXdzng+eg1su1btRU/PFdGocOworxivIwPXYIjWpOEYON+aAKm4ASIG11sa9Rk9UfWUFiiAl5hOkJ6KQT/JJWy88A3H3Sv2iyMoNN/4Bfem2Qqfg+bCD4Gteg8t06lEqDu2uD8wmkJ9aS9U+mbB0nERZ9dECiu7m+gZ3K+cHTLUIKLbXI/t4X7TRgsmcBZPdBOSriPc22yC/0NyCMw15PBMLq6m6rkFJXC1ctBFsizB0b6itvt58ZjPZfxHmN4wRouPOB7hKfTNYkUnskLM/UlW8v1yoG/dn2Ugi/3ULF6enZuOlqoC54VW+qLnZZtXvrfVrvACkNZqSgN5UNKhppVMxdZxB+o3cJyDYnWYpPi5J0tcszj4PYVBvx99JzrE2emdcIMrbj1FrLgtTBfheRwSYbY29i5CBljpL9K2Z5AxO+SM+TUW70kM4LLhJvTvZka9TIlp2i8gOmgNBexf2pMJRQMcAu7vpUhR0fzf/O0Bxglhr4yxnpTMTRMbPBp9LC3ibMAdZVYFl558FVYBGNcmfuh2Rkcw2bPu2Ey427QfIdBzgmdqFsAGQmRy2/zhOxtvWa0pciEnG0wf+MB/gxjQ/QOznP7OtzVsLOTHAET0DynInx99mpHyV26EskUGUEjnlzmTg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
